import type { NextPage } from 'next'
import Head from 'next/head';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta
          name='coxinha'
          content='Generated by create next app'
        />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <h1>Welcome</h1>
      </main>

      <footer></footer>
    </div>
  );
};

export default Home
